name: 'LaTeX to PDF'
description: 'Compile LaTeX into PDF file'
inputs:
  latex_path:
    description: 'The path of source LaTeX files'
    required: true
    default: './'
outputs:
  pdf_path:
    description: 'The path of PDFs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.latex_path }}